__title__ = 'XMind'
__description__ = '修改后的读取xmind模块'
__keywords__ = '修改后的读取xmind模块',
__url__ = 'https://github.com/TitanRisen'
__author__ = 'HONG'
__author_email__ = '123456@qq.com'
__version__ = '1.2.0'
__license__ = 'MIT'
__cake__ = u'\u2728 \U0001f370 \u2728'
